theme: jekyll-theme-minimal
logo: /figs/logo.png
title: Technical Writing in LaTeX
description: Harvey Mudd College
show_downloads: false
google_analytics:
relative_links:
  enabled:     true
  collections: false
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true
